language: java

# Our validator actually lives in the CKAN repo.
# --depth=1 is because we don't need full history.

install:
    - git clone --depth=1 https://github.com/KSP-CKAN/CKAN.git

# Our test is merely checking that all the ckan files validate
# against the current spec. We exclude the CKAN directory we just
# checked out.

script:
    - CKAN/bin/ckan-validate $(find . -path ./CKAN -prune -o -name '*.ckan' -print)
